version: "2.2"

dependencies:
  - project: madisonewebb/joda-time
    mapping:
      dependencies:
        default:
          - source: master
            target: master
      dependant:
        default:
          - source: master
            target: master

default:
  build-command:
    current: mvn -B -U -DskipTests -s .github/maven-settings.xml deploy
    upstream: mvn -B -U -DskipTests -s .github/maven-settings.xml install
