# build does not work on Java 9 or later as Java 5 is not a valid target

name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write
  security-events: write  # for github/codeql-action

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_ARGS: -e -B -ntp -DtrimStackTrace=false

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  #v4.2.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12  #v4.7.0
      with:
        java-version: 8
        distribution: 'temurin'
        cache: 'maven'

    - name: Maven version
      run: |
        mvn --version
        mkdir -p target

    - name: Initialize CodeQL
      uses: github/codeql-action/init@70df9def86d22bf0ea4e7f8b956e7b92e7c1ea22  #codeql-bundle-v2.20.7
      with:
        languages: java

    - name: Maven build
      run: |
        mvn install site

    - name: Set up JDK 17 for downstream builds
      if: ${{ success() }}
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12  #v4.7.0
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Run downstream build chain (build spring-petclinic)
      if: ${{ success() }}
      uses: kiegroup/github-action-build-chain@v3.5.9
      with:
        definition-file: https://raw.githubusercontent.com/madisonewebb/spring-petclinic/master/.ci/build-chain.yaml
        flow-type: full_downstream
        starting-project: madisonewebb/joda-time
        skip-project-execution: madisonewebb/joda-time
        logger-level: debug
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@70df9def86d22bf0ea4e7f8b956e7b92e7c1ea22  #codeql-bundle-v2.20.7
